### ISSUE TITLE
machine-failure-predictions classic model

### ISSUE THREAD

**Issue by tarekyehya** [tarekyehya/GenDrive#1]
dateset = https://www.kaggle.com/datasets/dineshmanikanta/machine-failure-predictions
Notebook and python code ( after finish the notebook, convert the code into methods and classes follow the MVC)

**Comment by tarekyehya** [comment]
keep it simple.

**Comment by tarekyehya** [comment]
the model directoy in src refer to M in MVC, it's a directory to hold the classes that work with data, look at the project now to know more,

you can keep the ML model in a new directory outside the src


you should build a class in the controller to have a method like predict or train if you want, in the predict as example, you will call the data of sensors of the model of sensors then take the relevant data to you then predict, we can call it as predict() without args.

Thanks.

**Comment by Axxaa9** [comment]
@tarekyehya, please review the progress. I couldn't test the model with MongoDB because I had a problem with my Docker application. Please share the test results with me.

**Comment by tarekyehya** [comment]
@Axxaa9 okay, ISA i will work in this now and i will ISA solve some small problems,
Your work is very pretty.

Take another Task ^^

Thanks Alaa

**Comment by tarekyehya** [comment]
Share the problem of the docker, ISA we can help
